### ISSUE TITLE
4fd6ee9 breaks compatibility with 88a1ac8

### ISSUE THREAD

**Issue by jdkleuver** [Tautau05/Discord-Bot#4]
The for loop in 4fd6ee9 at line 38 will never set template_found to true if meme_id is passed as a string instead of as the ID.

Also 'memes' does not contain every possible meme only the most popular ones. If user decides to use a less popular meme by it's ID it will fail.

Suggested fix: perform this check on the return value of the http request instead, the value of "success" in the json will be false if the template does not exist

**Comment by Tautau05** [comment]
Thanks i didn't think of that.
I just uploaded the new version.
